### ISSUE TITLE
Enhancing lipm_walking_controller with Additional States: Exploring Extension and Plugin Options

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/lipm_walking_controller#49]
@stephane-caron, @gergondet 

I would like to incorporate additional states into the `lipm_walking_controller`. However, my preference is to introduce them using either an extension, such as `FootSteps_Planner`, or a plugin, like `ExternalFootstepPlanner`. Is it feasible to implement these changes in either of these ways?

**Comment by gergondet** [comment]
Hi @Saeed-Mansouri 

Plugins are not meant to interact with the controller but rather to provide additional functionalities. Whereas states are meant to be a part of the control loop.

An intrusive approach would be to create additional states inside LIPMWalking and reprogram its FSM to accomodate the new states.

Another possible approach is to derive your new controller from the lipm_walking_controller

1. We find the package in CMake

```cmake
find_package(lipm_walking_controller REQUIRED)
target_link_libraries(MyController PUBLIC lipm_walking_controller::lipm_walking_controller)
```

2. We use lipm_walking::Controller as base

```cpp
#include <lipm_walking/Controller.h>

struct MyController : public lipm_walking::Controller
{
// Same as regular FSM controller
};
```

```cpp
// Same as regular FSM controller but instead of calling mc_control::fsm::Controller function we call lipm_walking::Controller functions

MyController::MyController(mc_rbdyn::RobotModulePtr rm, double dt, const mc_rtc::Configuration & cfg)
: lipm_walking::Controller(rm ,dt, cfg)
{
}

// etc...
```

We configure the controller to use the LIPMWalking states

```yaml
# LIPM_WALKING variables come from find_package(lipm_walking)
StatesLibraries:
- "@MC_STATES_DEFAULT_INSTALL_PREFIX@"
- "@MC_STATES_INSTALL_PREFIX@"
- "@LIPM_WALKING_STATES_LIBRARIES@"

# Where to look for state files
StatesFiles:
- "@MC_STATES_DEFAULT_INSTALL_PREFIX@/data"
- "@MC_STATES_INSTALL_PREFIX@/data"
- "@LIPM_WALKING_STATES_FILES@"

# ...
states:
  WalkInternal:
    base: Meta
    transitions:
    - [LIPMWalking::Standing, DoubleSupport, LIPMWalking::DoubleSupport]
    - [LIPMWalking::DoubleSupport, SingleSupport, LIPMWalking::SingleSupport]
    - [LIPMWalking::DoubleSupport, Standing, LIPMWalking::Standing]
    - [LIPMWalking::SingleSupport, DoubleSupport, LIPMWalking::DoubleSupport]
    configs:
      LIPMWalking::Standing:
        autoplay: false
        autoplay_plans: [external]
  
  WalkFSM:
    base: Parallel
    states: [LIPMWalking::RunStabilizer, WalkInternal]
MyControllerMain:
  base: Parallel
  states: [ WalkFSM, MyControllerMeta]
```

(sorry but we don't have a public example of this)
